---
# tasks file for AsianChris.docker

- name: Add Docker on Ubuntu systems
  include_tasks: os/ubuntu.yml

- name: Add User to group
  user: name={{ ansible_ssh_user }} groups=docker append=yes
  become: yes
  become_method: sudo
