---
# tasks file for AsianChris.docker

- name: Add Docker GPG Key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present
  become: yes
  become_method: sudo

- name: Add Docker Repository
  apt_repository: 
    repo: deb https://download.docker.com/linux/ubuntu/ {{ ansible_distribution_release }} stable
    state: present
  become: yes
  become_method: sudo
  register: docker_repo_added

- name: Apt update cache
  apt: update_cache=yes
  become: yes
  become_method: sudo
  when: docker_repo_added.changed

- name: Install Docker Engine
  apt: pkg={{item}} state=present
  become: yes
  become_method: sudo
  with_items:
    - docker-ce

- name: Install Docker SDK for Python
  pip: name=docker-py state=present
  become: yes
  become_method: sudo
